# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  preview-build:
    runs-on: ubuntu-latest
    steps:
    # Put steps here to build, and check your site.
    - name: Clear Cloudflare cache
      uses: Cyb3r-Jak3/actions-cloudflare-pages@v1.0.0
      with:
        account: ${{ secrets.CLOUDFLARE_ZONE }}
        project: ${{ secrets.CLOUDFLARE_PROJECT }}
        email: ${{ secrets.CLOUDFLARE_EMAIL }}
        global_token: ${{ secrets.CLOUDFLARE_KEY }}

  grab-the-preview-url:
    runs-on: ubuntu-latest
    steps:
    # Put steps here to build, and check your site.
    - run: sleep 30
    - name: cloudflare-preview-url
      uses: zentered/cloudflare-preview-url@v1.0.0
      id: cloudflare_preview_url
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_KEY }}
        CLOUDFLARE_ACCOUNT_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ZONE }}
      with:
        cloudflare_project_id: ${{ secrets.CLOUDFLARE_PROJECT }}
        wait_until_ready: true
    - name: Get URL
      run: echo "https://${{ steps.cloudflare_preview_url.outputs.preview_url }}"
